services:

  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: med-card
      POSTGRES_USER: med
      POSTGRES_PASSWORD: 123
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=med
      - MINIO_ROOT_PASSWORD=12345678
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - ./.minio/data:/minio